[package]
name = "three-cubes"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "three-cubes"
path = "src/main.rs"

[dependencies]
igl-rs = { path = "../igl-rs" }
igl-sys = { path = "../igl-sys" }
winit = "0.29"
raw-window-handle = "0.6"
glam = "0.25"
